config/routes.rb
Rails.application.routes.draw do
  resources :charges, only: [:create] do
    member do
      get 'success'
      get 'cancel'
    end
  end

  resources :homes
  resources :orders
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :products

  root to: 'homes#index'
end

app/controllers/homes_controller.rb
require 'json'

class HomesController < ApplicationController
  Stripe.api_key = 'sk_test_4eC39HqLyjWDarjtT1zdp7dc'

  # before_action :authenticate_user!
  before_action :set_product, :set_all_product, only: %i[edit update destroy]
  before_action :summary, only: %i[show edit update destroy]

  def index
    @products = Product.cart(get_zenbil)
  end

  def show
    @zenbil = Order.cart(get_zenbil)
  end

  def destroy
    unless @all_product_orders.empty?
      @whole_product = false
      if params[:all].eql?('1')
        @whole_product = true
        Order.where(product_id: @product.id, zenbil: get_zenbil).destroy_all
        @all_product_orders = @all_product_orders.map do |order|
          order unless order.product_id.eql?(@product.id)
        end
      else
        @deleted_order = Order.destroy(@all_product_orders[0].id)
        @all_product_orders = @all_product_orders.drop(1)
      end
    end

    respond_to do |format|
      format.js { render 'destroy', layout: false }
    end
  end

  def create
    product_params.each do |order, _i|
      set_zenbil
      @order = current_user.orders.build(product_id: order.to_i, zenbil: get_zenbil)
      if @order.save
        # format.json { render :show, status: :created, location: @order }
      else
        puts 'error'
      end
    end

    redirect_to root_url and return

    # redirect_to home_url(:id => get_zenbil) and return
    # format.html { redirect_to home_url, notice: 'Event was successfully destroyed.' }
  end

  def edit; end

  def update
    @order = Order.new(product_id: @product.id, user_id: get_stranger_id, zenbil: get_zenbil)
    if @order.save
      flash[:success] = 'Product Added'
    else
      flash[:error] = 'Something went wrong'
    end

    respond_to do |format|
      format.js { render 'update', layout: false }
    end
  end

  def checkout
    session = Stripe::Checkout::Session.create({
                                                 payment_method_types: ['card'],
                                                 line_items: [{
                                                   price_data: {
                                                     currency: 'usd',
                                                     product_data: {
                                                       name: 'T-shirt'
                                                     },
                                                     unit_amount: 2000
                                                   },
                                                   quantity: 1
                                                 }],
                                                 mode: 'payment',
                                                 success_url: "https://yoursite.com/success.html",
                                                 cancel_url: 'https://example.com/cancel',
                                               })

    { id: session.id }.to_json
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def set_all_product
    @all_product_orders = Order.where(product_id: params[:id], user_id: get_stranger_id, zenbil: get_zenbil)
  end

  def product_param
    params.require(:id).to_i
  end

  def summary
    @order_summary = { estimated_total: 0, total_product: 0 }
    @zenbil = Order.cart(get_zenbil)

    if @zenbil && !@zenbil.empty?
      @order_summary[:estimated_total] = @zenbil.map { |order| order.price * order.pieces }.reduce(:+)
      @order_summary[:total_product] = @zenbil.length
    end

    @order_summary
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def get_zenbil
    zenbil = session[:current_zenbil]
    zenbil || set_zenbil
  end

  def set_zenbil
    session[:current_zenbil] = SecureRandom.uuid
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_heading.html.erb
<section class="w-full h-full md:h-screen bg-cover md-right-top bg-left-top bg-fixed bg-no-repeat bg-img-top">
  <div class="w-full h-full flex justify-center md:pt-44 text-white" style="background-color: rgba(0,0,0,0.5);">
    <div class="flex flex-col items-center">
      <%= image_tag('logo.png', class: 'my-2 w-20 md:w-48') %>
      <p class="text-5xl md:text-8xl font-bold py-4 text-opacity-100 playfair">
        Guada Baltena
      </p>
      <p class="px-2 pb-8 mx-auto text-center text-md lg:w-1/2 md:text-xl mt-4 andika font-hairline">Imported from
        Ethiopia, our products are 100% authentic. Whether you’re an Ethiopian food veteran, or you’re looking to try
        Ethiopian cuisine for the first time, you’ll want to be well-acquainted with our wide variety of East African
        spices and seasonings.</p>
    </div>
  </div>
</section>

app/views/homes/_product.html.erb
<div class="rounded-lg h bg-white mx-2 my-4 shadow-sm w-100 md:w-1/3 lg:w-1/4">
  <%= cl_image_tag(product.files[0].key, width: 200, crop: :scale, alt: product.name, class: 'p-2 rounded-md object-cover h-52 w-full object-center') %>
  <div class="flex flex-col">
    <div class="flex items-center content-center justify-between p-4">
      <div class="flex flex-col">
        <a href="detail.html">
          <p class="andika text-lg hover:text-red-500 hover:underline"><%= product.name %></p>
        </a>
        <p class="text-gray-400 roboto text-sm">16 Oz</p>
      </div>
      <p class="text-red-500 anika font-bold">$ <%= product.price %></p>
    </div>
    <div class="flex justify-between p-2">
      <div class="w-1/3 items-center mb-2 justify-between flex">
        <%= link_to home_path(product.id),
                    class: "rounded-xl mx-1 p-2 border border-transparent hover:border-white
                     hover:bg-red-300 bg-red-200 text-white",
                    remote: true, method: :delete, disable_with: "Processing..." do %>
          <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="16" height="16"
               viewBox="0 0 172 172" style=" fill:#ffffff;">
            <g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt"
               stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0"
               font-family="none" font-size="none"
               style="mix-blend-mode: normal">
              <path d="M0,172v-172h172v172z" fill="none"></path>
              <g fill="#ffffff">
                <path
                  d="M28.66667,74.53333c-4.13529,-0.05848 -7.98173,2.11417 -10.06645,5.68601c-2.08471,3.57184 -2.08471,7.98948 0,11.56132c2.08471,3.57184 5.93115,5.74449 10.06645,5.68601h114.66667c4.13529,0.05848 7.98173,-2.11417 10.06645,-5.68601c2.08471,-3.57184 2.08471,-7.98948 0,-11.56132c-2.08471,-3.57184 -5.93115,-5.74449 -10.06645,-5.68601z">
                </path>
              </g>
            </g>
          </svg>
        <% end %>

        <p id="totalProduct_<%= product.id %>" class="andika text-bold mx-1 text-xl text-gray-500"><%= product.pieces %></p>

        <%= link_to home_path(product.id),
                    class: "rounded-xl mx-1 border border-transparent hover:border-white p-2
                     hover:bg-red-600 bg-red-500 text-white",
                    remote: true, method: :put, disable_with: "Processing..." do %>
          <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="16" height="16"
               viewBox="0 0 172 172" style=" fill:#ffffff;">
            <g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt"
               stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0"
               font-family="none" font-size="none"
               style="mix-blend-mode: normal">
              <path d="M0,172v-172h172v172z" fill="none"></path>
              <g fill="#ffffff">
                <path
                  d="M85.83203,17.04323c-6.32845,0.09274 -11.38527,5.2949 -11.2987,11.62344v45.86667h-45.86667c-4.13529,-0.05848 -7.98173,2.11417 -10.06645,5.68601c-2.08471,3.57184 -2.08471,7.98948 0,11.56132c2.08471,3.57184 5.93115,5.74449 10.06645,5.68601h45.86667v45.86667c-0.05848,4.13529 2.11417,7.98173 5.68601,10.06645c3.57184,2.08471 7.98948,2.08471 11.56132,0c3.57184,-2.08471 5.74449,-5.93115 5.68601,-10.06645v-45.86667h45.86667c4.13529,0.05848 7.98173,-2.11417 10.06645,-5.68601c2.08471,-3.57184 2.08471,-7.98948 0,-11.56132c-2.08471,-3.57184 -5.93115,-5.74449 -10.06645,-5.68601h-45.86667v-45.86667c0.04237,-3.09747 -1.17017,-6.08033 -3.36168,-8.26973c-2.1915,-2.18939 -5.17553,-3.39907 -8.27296,-3.35371z">
                </path>
              </g>
            </g>
          </svg>
        <% end %>
      </div>
      <%= link_to home_path(product.id),
                  remote: product.pieces.positive? ? false : true, method: (product.pieces.positive? ? :get : :put),
                  class: 'andika mb-2 rounded-full px-4 py-2 border border-gray-300
                      hover:text-white hover:bg-red-500 hover:border-transparent',
                  disable_with: "Processing..." do %>
        <%= tag.span product.pieces.positive? ? 'View Cart' : 'Add To Cart', id: "addToCart_" + product.id.to_s %>
      <% end %>
    </div>
  </div>
</div>

app/views/homes/_search.html.erb
<div class="container mx-auto flex flex-col md:flex-row justify-between px-16">
  <div class="md:w-1/2">
    <p class="playfair mt-10 py-4 fon-700 text-5xl">Our Products</p>
    <p class="text-gray-500 andika tracking-wide">All of our products are imported from our Ethiopian headquarters.
      Best of all, we take pride in providing our customers with ingredients that are all-natural, non-GMO, and free
      of preservatives. It doesn’t get better than that! </p>
  </div>
  <div class="flex pt-12 items-center z-0">
    <div class="relative text-gray-600">
      <input type="search" name="serch" placeholder="Search"
             class="bg-white h-10 px-5 pr-10 rounded-full text-sm focus:outline-none">
      <button type="submit" class="absolute right-0 top-0 mt-3 mr-4">
        <svg class="h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg"
             xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px"
             viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve"
             width="512px" height="512px">
          <path
            d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
        </svg>
      </button>
    </div>
    <!-- <p class="mt-8 andika py-4 text-gray-500">Lorem Ipsum</p> -->
  </div>
</div>

app/views/homes/create.html.erb
<h1>Homes#create</h1>
<p>Find me in app/views/homes/create.html.erb</p>

app/views/homes/destroy.js.erb
addBtn = document.getElementById('addToCart_' +<%= @product.id.to_s %>)
totalP = document.getElementById('totalProduct_' +<%= @product.id.to_s %>)
productCard = document.getElementById('product_' +<%= @product.id.to_s %>)


<% if @whole_product %>
      if (productCard) {
          productCard.parentElement.removeChild(productCard)
      }
<% end %>

<% if @all_product_orders.length > 0 %>
  if (addBtn) {
      addBtn.innerText = "View Cart";
  }

  if (totalP) {
      totalP.innerText = "<%= @all_product_orders.length %>";
  }

<% else %>

  if (addBtn) {
      addBtn.innerText = "Add To Cart";
  }

  if (totalP) {
      totalP.innerText = '0';
  }

<% end %>

app/views/homes/edit.html.erb
<h1>Homes#edit</h1>
<p>Find me in app/views/homes/edit.html.erb</p>

app/views/homes/index.html.erb
<%= render 'heading' %>

<section class="bg-gray-100 py-6" id="shop">
  <%= render 'search' %>
  <div class="container mx-auto flex justify-center flex-wrap my-12">
    <% @products.each do |product| %>
      <%= render 'product', product: product %>
    <% end %>
  </div>
</section>

app/views/homes/show.html.erb
<section class="bg-gray-100 pt-20">
  <!-- <p class="text-gray-700 text-2xl text-center">Items in Cart</p> -->
  <div class="md:flex flex-col mx-auto items-center px-10 lg:px-0 lg:container">

    <div class="lg:w-2/3 w-100 grid grid-cols-12 gap-10 p-4">
      <% @zenbil.each { |order| %>
        <div class="rounded-lg col-span-12 md-col-span-5 lg:col-span-4 min-w-min bg-white mx-2 my-4 shadow-sm w-full" id="product_<%= order.id %>">
          <%= cl_image_tag(order.files[0].key, width: 200, crop: :scale, alt: order.name, class: 'p-2 rounded-md object-cover h-52 w-full object-center') %>
          <div class="flex flex-col">
            <div class="flex items-center content-center justify-between p-4">
              <div class="flex flex-col">
                <a href="detail.html">
                  <p class="andika text-lg hover:text-red-500 hover:underline"><%= order.name %></p>
                </a>
                <p class="text-gray-400 roboto text-sm">16 Oz</p>
              </div>
              <p class="text-red-500 anika font-bold">$ <%= order.price %></p>
            </div>
            <div class="flex justify-between p-2">
              <div class="w-1/3 items-center mb-2 justify-between flex">
                <%= link_to home_path(order.id),
                            class: "rounded-xl mx-1 border border-transparent hover:border-white p-2
                     hover:bg-red-600 bg-red-500 text-white",
                            remote: true, method: :put, disable_with: "Processing..." do %>
                  <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="16" height="16"
                       viewBox="0 0 172 172" style=" fill:#ffffff;">
                    <g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt"
                       stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0"
                       font-family="none" font-size="none"
                       style="mix-blend-mode: normal">
                      <path d="M0,172v-172h172v172z" fill="none"></path>
                      <g fill="#ffffff">
                        <path
                          d="M85.83203,17.04323c-6.32845,0.09274 -11.38527,5.2949 -11.2987,11.62344v45.86667h-45.86667c-4.13529,-0.05848 -7.98173,2.11417 -10.06645,5.68601c-2.08471,3.57184 -2.08471,7.98948 0,11.56132c2.08471,3.57184 5.93115,5.74449 10.06645,5.68601h45.86667v45.86667c-0.05848,4.13529 2.11417,7.98173 5.68601,10.06645c3.57184,2.08471 7.98948,2.08471 11.56132,0c3.57184,-2.08471 5.74449,-5.93115 5.68601,-10.06645v-45.86667h45.86667c4.13529,0.05848 7.98173,-2.11417 10.06645,-5.68601c2.08471,-3.57184 2.08471,-7.98948 0,-11.56132c-2.08471,-3.57184 -5.93115,-5.74449 -10.06645,-5.68601h-45.86667v-45.86667c0.04237,-3.09747 -1.17017,-6.08033 -3.36168,-8.26973c-2.1915,-2.18939 -5.17553,-3.39907 -8.27296,-3.35371z">
                        </path>
                      </g>
                    </g>
                  </svg>
                <% end %>
                <p id="totalProduct_<%= order.id %>" class="andika text-bold mx-1 text-xl text-gray-500"><%= order.pieces %></p>
                <%= link_to home_path(order.id),
                            class: "rounded-xl mx-1 p-2 border border-transparent hover:border-white
                     hover:bg-red-300 bg-red-200 text-white",
                            remote: true, method: :delete, disable_with: "Processing..." do %>
                  <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="16" height="16"
                       viewBox="0 0 172 172" style=" fill:#ffffff;">
                    <g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt"
                       stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0"
                       font-family="none" font-size="none"
                       style="mix-blend-mode: normal">
                      <path d="M0,172v-172h172v172z" fill="none"></path>
                      <g fill="#ffffff">
                        <path
                          d="M28.66667,74.53333c-4.13529,-0.05848 -7.98173,2.11417 -10.06645,5.68601c-2.08471,3.57184 -2.08471,7.98948 0,11.56132c2.08471,3.57184 5.93115,5.74449 10.06645,5.68601h114.66667c4.13529,0.05848 7.98173,-2.11417 10.06645,-5.68601c2.08471,-3.57184 2.08471,-7.98948 0,-11.56132c-2.08471,-3.57184 -5.93115,-5.74449 -10.06645,-5.68601z">
                        </path>
                      </g>
                    </g>
                  </svg>
                <% end %>

              </div>
              <%= link_to home_path(order.id, all: 1),
                          class: "rounded-xl p-1 border border-transparent hover:border-white
                           bg-white hover:bg-gray-100 text-white",
                          remote: true, method: :delete, disable_with: "Processing..." do %>
                <img class="self-center" src="https://img.icons8.com/windows/32/fa314a/trash.png"/>
              <% end %>
            </div>
          </div>
        </div>

      <% } %>
    </div>

    <div class="flex flex-col bg-white w-1/2 lg:w-2/5 h-1/2 p-4 my-14 items-center rounded-lg shadow-sm">
      <p class="playfair text-3xl py-4 text-center">Order Summary</p>
      <div class=" flex andika justify-between mx-auto w-4/5 text-xl py-2">
        <p>Estimated Price</p>
        <p>$<span id="estimated_total"><%= @order_summary[:estimated_total] %></span></p>
      </div>
      <div class="mb-12 flex andika justify-between mx-auto w-4/5 text-xl py-2">
        <p>Total Product</p>
        <p id="total_product"><%= @order_summary[:total_product] %></span></p>
      </div>
      <a id="checkout-button" class="cursor-pointer bg-red-500 px-4 py-2 font-bold rounded andika mt-4 text-white">
        Proceed to Checkout</a>
      <a href="<%= root_path %>#shop" class="text-gray-400 hover:underline andika py-2 text-sm hover:text-gray-600">Continue
        Shopping</a>
    </div>
  </div>
</section>

<script type="text/javascript">
    // Create an instance of the Stripe object with your publishable API key
    const api_key = 'pk_test_51I1ul4H1O6SVZlgxbPI1PHFAwEtNawhPe8Dk3LaDy9S98XTODmIzUFeDUoCrzGAZcu0qZhIP7rS7VDSgWixXwPqV00AJ7hwSNo'
    var stripe = Stripe(api_key);
    var checkoutButton = document.getElementById("checkout-button");
    checkoutButton.addEventListener("click", function () {

        if (!stripe) {
            location.reload();
        }

        let bdy = JSON.stringify({authenticity_token: "<%= form_authenticity_token %>"})
        fetch("<%= charges_url %>", {
            headers:  {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            body: bdy,
            method: "POST",
            credentials: 'same-origin'
        }).then(function (response) {

            return response.json();
        }).then(function (session) {
            console.log(session)
            return stripe.redirectToCheckout({sessionId: session.id});
        }).then(function (result) {
            if (result.error) {
                alert(result.error.message);
            }
        }).catch(function (error) {
            console.error("Error:", error);
        });
    });
</script>

app/views/homes/update.js.erb
addBtn = document.getElementById('addToCart_' +<%= @all_product_orders[0].product_id.to_s %>)
<% if @all_product_orders.length > 0 %>
    if (addBtn) {
        addBtn.innerText = "View Cart";
        addBtn.parentElement.removeAttribute("data-remote")
        addBtn.parentElement.removeAttribute("data-method")
    }
<% else %>
    if (addBtn) {
        addBtn.innerText = "Add To Cart";
        addBtn.parentElement.setAttribute("data-remote", "true")
        parentElement.setAttribute("data-method", "put")
    }
<% end %>

document
        .getElementById('totalProduct_' +<%= @all_product_orders[0].product_id.to_s %>)
        .innerText = "<%= @all_product_orders.length %>";

 et = document
    .getElementById('estimated_total');
 tp = document
    .getElementById('total_product');

if (et) {
    et.innerText = "<%= @order_summary[:estimated_total] %>"
}

if (tp) {
    tp.innerText = "<%= @order_summary[:total_product] %>"
}